### ISSUE TITLE
Unable to chown files using jboss/wildfly image

### ISSUE THREAD

**Issue by dkfi** [jboss-dockerfiles/wildfly#11]
In my Dockerfile I ADD a file and then RUN chown on it but I get a permission denied error. The file gets added as user root but I would like it to be set as jboss:jboss. I then ran "docker exec -it my_id bash" to inspect the container and noticed that the shell starts with user jboss. Is there a way to become root user or to be able to chown the file? I also wonder how the shell restriction to jboss user was done.

**Comment by goldmann** [comment]
What you described above is expected, since we do not use `root` account to run WildFly. Use following statement in your `Dockerfile`

```
USER root
RUN chown ...
USER jboss
```

Regarding the question how the user switch was done - the answer is [here](https://github.com/jboss-dockerfiles/base/blob/5612f798dab6a35453da936997eb9d6f1fda6d7a/Dockerfile#L20).

**Comment by goldmann** [comment]
Closing.
