### ISSUE TITLE
Missing EXPOSE 9090 ?

### ISSUE THREAD

**Issue by chevdor** [jboss-dockerfiles/wildfly#26]
Hello,

I just tested 9.0.1 Final and once the container is started, I can reach the port 8080.
However I cannot reach the port 9090.
I see in the logs that the admin console is served on 127.0.0.1:9090 and I did map 9090 to a port however I cannot reach the admin console.

Can it be an issue with the image?

**Comment by chevdor** [comment]
The container starts wildfly using the following command:

```CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]````

This does not allow admin console access remotely. For that, the container should start as:
```CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0" ] ````

Details here: 
https://docs.jboss.org/author/display/WFLY8/Admin+Guide?_sscc=t#AdminGuide-WebManagementInterface

I understand that the admin consol is *not* enabled by default for security reason so I close this 'issue'.

**Comment by chevdor** [comment]
See #27

**Comment by goldmann** [comment]
Dockerfile for this image is not missing the `EXPOSE 9090` instruction. The reason is that the management port is not bound to the eth0 interface and thus not available. It does not make sense to expose a port which is not reachable. Additionally there is no intent to bind the management port, becuase in many (most) cases management port is not used at all.

You are free to create an image that bases on `jboss/wildfly` and exposes ports or adds the management port, but `jboss/wildfly` needs to be generic.
