### ISSUE TITLE
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m

### ISSUE THREAD

**Issue by patrickd1** [jboss-dockerfiles/wildfly#38]
Hello,

My name is Patrick Dallaire, I am a intern for [Tecsys Inc.](http://www.tecsys.com/) in Montreal Canada.

We've been using Wildfly for a long time and for the first time now we are experimenting with Docker.
Now this isn't a big deal, in fact everything still works, but every time we use 'docker log containerName' command we could see the following error message:

**OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0**

According to what I’ve read, the command line argument for java, -XX:MaxPermSize, was deprecated in Java 8.

[Oracle compatibility-guide](http://www.oracle.com/technetwork/java/javase/8-compatibility-guide-2156366.html)
[Oracle tech notes](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html)

This argument is probably used by the wildfly scripts we use to launch our instance.  In our case we use:
`/opt/jboss/wildfly/bin/standalone.sh -c standalone-full.xml -b 0.0.0.0`

The deprecated argument shows up in at the following locations inside our running container:
```
[root@feaf7375338f jboss]# grep -rnw '/opt/jboss' -e "JAVA_OPTS" | egrep 'MaxPermSize'
/opt/jboss/wildfly/bin/appclient.conf:45:   JAVA_OPTS="-Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true"
/opt/jboss/wildfly/bin/appclient.conf.bat:43:set "JAVA_OPTS=-Xms64M -Xmx512M -XX:MaxPermSize=256M"
/opt/jboss/wildfly/bin/domain.conf:45:   JAVA_OPTS="-Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true"
/opt/jboss/wildfly/bin/domain.conf.bat:46:set "JAVA_OPTS=-Xms64M -Xmx512M -XX:MaxPermSize=256M"
/opt/jboss/wildfly/bin/standalone.conf:50:   JAVA_OPTS="-Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true"
/opt/jboss/wildfly/bin/standalone.conf.bat:49:set "JAVA_OPTS=-Xms64M -Xmx512M -XX:MaxPermSize=256M"
```

Even though this isn't a big a deal, especially since I can redirect the standard error, I thought you should still be informed.

Have a nice day.

**Comment by goldmann** [comment]
Hello Patrick!

Thank you for you detailed report. Indeed, this setting was removed in JDK 8, we are aware of this. The `jboss/wildfly` Docker image tries to be as close as it can be the same as the distribution downloaded from wildfly.org. This means that we refrain to do any unnecessary changes to the codebase. We modify it only where it is strictly required to be able to run it in a Docker container.

Since this does not affect running I vote to refrain from modifying the code.

The best idea is to open a ticket upstream: https://issues.jboss.org/projects/WFLY/summary so it can be fixed everywhere.

Thanks!
