### ISSUE TITLE
jboss/wildfly:15.0.0.Final - wrong java version

### ISSUE THREAD

**Issue by GitHubAlainM** [jboss-dockerfiles/wildfly#92]
Hello,
It seems that there is an issue with the openjdk version embedded with jboss/wildfly image with tag 15.0.0.Final.
The expected Java version is openjdk8 but the one provided is openjdk11.
It seems that the docker image has been built with the Dockerfile of version 15.0.0.Final-1 instead of version 15.0.0.Final

Dockerfile of 15.0.0.Final
FROM jboss/base-jdk:8

and if you compare with Dockerfile of 15.0.0.Final-1:
FROM jboss/base-jdk:11

If I build my own image from your Dockerfile, everything is working as expected but if I pull your image it comes with openjdk11.

Kind regards,
Alain

**Comment by goldmann** [comment]
WildFly 15 should use JDK 11. This was the decision we made. The 15.0.0.Final was incorrectly tagged with JDK8, so a new, correct 15.0.0.Final-1 tag was added to prevent re-tagging.

**Comment by spikedboy** [comment]
Wasn't tag 15.0.0.Final meant to be Wildfly15 with JDK8 and tag 15.0.1.Final meant to be Wildfly15 with JDK11?
That is what I understood some months ago when I made a Dockerfile which depended on tag 15.0.0.Final  wanting explicitly to have JDK8. 
Now we don't have an official image with JDK8 and Wildfly15.
We had some parameters passed to the JVM through a servergroup in our domain.xml.
It blew up today because these parameters are not the same for JDK11 as they are for JDK8.
Could we not have a tag for wildfly15 and JDK8?

**Comment by goldmann** [comment]
This image is provided with a single, default JDK which is JDK 11 currently. You are free to extend this image and install OpenJDK 8 (or any other JDK) to satisfy your requirements.
